## Q-10. 
An Ad- Agency analyzed a dataset of online ads and used a machine learning
model to predict whether a user would click on an ad or not.
Dataset This is the Dataset You can use this dataset for this question.

In [1]:
import pandas as pd
df = pd.read_csv("ad_click_dataset.csv",nrows=100000, low_memory=False)
df

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,7336715753207296307,0,14102100,1005,0,85f751fd,c4e18dd6,50e219e0,5e3f096f,2347f47a,...,1,0,21611,320,50,2480,3,297,100111,61
99996,7337101895328835610,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15702,320,50,1722,0,35,-1,79
99997,7337105322498379543,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15702,320,50,1722,0,35,-1,79
99998,733733102451104166,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15708,320,50,1722,0,35,-1,79
99999,7337344694709593001,0,14102100,1002,0,cc1b7a47,7256c623,50e219e0,ecad2386,7801e8d9,...,0,0,21665,320,50,2493,3,35,-1,117

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                100000 non-null  uint64
 1   click             100000 non-null  int64
 2   hour              100000 non-null  int64
 3   C1                100000 non-null  int64
 4   banner_pos        100000 non-null  int64
 5   site_id           100000 non-null  object
 6   site_domain       100000 non-null  object
 7   site_category     100000 non-null  object
 8   app_id            100000 non-null  object
 9   app_domain        100000 non-null  object
 10  app_category      100000 non-null  object
 11  device_id         100000 non-null  object
 12  device_ip         100000 non-null  object
 13  device_model      100000 non-null  object
 14  device_type       100000 non-null  int64
 15  device_conn_type  100000 non-null  int64
 16  C14               100000 non-null  int64
 17  C15               100000 non-null  int64
 18  C16               100000 non-null  int64
 19  C17               100000 non-null  int64
 20  C18               100000 non-null  int64
 21  C19               100000 non-null  int64
 22  C20               100000 non-null  int64
 23  C21               100000 non-null  int64
dtypes: int64(14), object(9), uint64(1)
memory usage: 18.3+ MB

In [4]:
df.isna().sum().sum()

0

In [5]:
# Select columns with data type 'object' (categorical columns)
categorical_columns = df.select_dtypes(include='object')

# Select columns with numeric data types (numerical columns)
numerical_columns = df.select_dtypes(include=['int64', 'float64'])

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Iterate over each categorical column and encode its values
for col in categorical_columns:
    df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])

C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])
C:\Users\dell\AppData\Local\Temp\ipykernel_10960\3392204633.py:6: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, col] = label_encoder.fit_transform(df.loc[:, col])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                100000 non-null  uint64
 1   click             100000 non-null  int64
 2   hour              100000 non-null  int64
 3   C1                100000 non-null  int64
 4   banner_pos        100000 non-null  int64
 5   site_id           100000 non-null  int32
 6   site_domain       100000 non-null  int32
 7   site_category     100000 non-null  int32
 8   app_id            100000 non-null  int32
 9   app_domain        100000 non-null  int32
 10  app_category      100000 non-null  int32
 11  device_id         100000 non-null  int32
 12  device_ip         100000 non-null  int32
 13  device_model      100000 non-null  int32
 14  device_type       100000 non-null  int64
 15  device_conn_type  100000 non-null  int64
 16  C14               100000 non-null  int64
 17  C15               100000 non-null  int64
 18  C16               100000 non-null  int64
 19  C17               100000 non-null  int64
 20  C18               100000 non-null  int64
 21  C19               100000 non-null  int64
 22  C20               100000 non-null  int64
 23  C21               100000 non-null  int64
dtypes: int32(9), int64(14), uint64(1)
memory usage: 14.9 MB

In [8]:
df

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,104,742,2,656,23,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,104,742,2,656,23,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,104,742,2,656,23,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,104,742,2,656,23,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,881,439,0,656,23,...,1,0,18993,320,50,2161,0,35,-1,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,7336715753207296307,0,14102100,1005,0,475,595,6,269,6,...,1,0,21611,320,50,2480,3,297,100111,61
99996,7337101895328835610,0,14102100,1005,0,104,742,2,656,23,...,1,0,15702,320,50,1722,0,35,-1,79
99997,7337105322498379543,1,14102100,1005,0,104,742,2,656,23,...,1,0,15702,320,50,1722,0,35,-1,79
99998,733733102451104166,0,14102100,1005,0,104,742,2,656,23,...,1,0,15708,320,50,1722,0,35,-1,79
99999,7337344694709593001,0,14102100,1002,0,708,339,6,656,23,...,0,0,21665,320,50,2493,3,35,-1,117

In [9]:
# Separate features and target variable
X = df.drop(['id', 'click'], axis=1)
y = df['click']

In [11]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression
# Train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [13]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.82355