## Q-2.
Imagine you have a dataset where you have different features like Age ,
Gender , Height , Weight , BMI , and Blood Pressure and you have to classify the people into
different classes like Normal , Overweight , Obesity , Underweight , and Extreme Obesity by using
any 4 different classification algorithms. Now you have to build a model which
can classify people into different classes.
Dataset This is the Dataset You can use this dataset for this question.

In [1]:
## Import the necessary libraries:-
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("ObesityDataSet.csv")

In [3]:
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [4]:
data.shape

(2111, 17)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [6]:
data.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [7]:
data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [9]:
# Preprocess the dataset
encoder = LabelEncoder()
data['Gender'] = encoder.fit_transform(data['Gender'])
data['family_history_with_overweight'] = encoder.fit_transform(data['family_history_with_overweight'])
data['FAVC'] = encoder.fit_transform(data['FAVC'])
data['CAEC'] = encoder.fit_transform(data['CAEC'])
data['SMOKE'] = encoder.fit_transform(data['SMOKE'])
data['SCC'] = encoder.fit_transform(data['SCC'])
data['CALC'] = encoder.fit_transform(data['CALC'])
data['MTRANS'] = encoder.fit_transform(data['MTRANS'])
data['NObeyesdad'] = encoder.fit_transform(data['NObeyesdad'])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   int32
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   int32
 5   FAVC                            2111 non-null   int32
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   int32
 9   SMOKE                           2111 non-null   int32
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   int32
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   int32
 15  MTRANS                          2111 non-null   int32
 16  NObeyesdad                      2111 non-null   int32
dtypes: float64(8), int32(9)
memory usage: 206.3 KB

In [11]:
# Split the dataset into features (X) and target (y)
X = data.drop('NObeyesdad', axis=1)
y = data['NObeyesdad']

In [12]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Decision Tree Classifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
dt_predictions = dt_clf.predict(X_test)
dt_predictions

array([0, 4, 0, 0, 1, 0, 3, 5, 2, 0, 2, 4, 2, 3, 4, 6, 4, 3, 2, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 5, 6, 1, 0, 4, 2, 1, 1, 1, 1, 3, 1, 1,
       5, 0, 3, 1, 2, 3, 1, 1, 1, 5, 0, 6, 3, 3, 5, 3, 1, 4, 6, 0, 2, 2,
       1, 4, 0, 0, 6, 6, 0, 0, 5, 3, 3, 5, 4, 3, 1, 2, 3, 3, 2, 2, 1, 6,
       1, 6, 5, 3, 0, 5, 2, 0, 5, 2, 1, 3, 2, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 2, 1, 0, 2, 2, 3, 6, 1, 4, 3, 2, 6, 5, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 5, 2, 5, 6, 0, 0, 1, 3, 2, 4, 0, 2, 0, 0, 1, 3,
       2, 5, 6, 5, 0, 0, 5, 1, 2, 0, 3, 0, 3, 1, 5, 6, 1, 6, 3, 4, 2, 6,
       2, 5, 2, 1, 1, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 1, 3, 2,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 2,
       4, 6, 3, 5, 3, 6, 0, 4, 5, 5, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 6, 2, 1, 2, 2, 0, 5, 2, 0, 1, 1, 6, 2, 3, 2, 1, 4, 4, 5, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 5, 2, 3, 2, 3, 4, 3, 0, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 0, 2, 0, 5, 3, 3, 6, 6, 1, 5, 0, 0, 5, 5, 6, 5,
       6, 4, 5, 3, 1, 4, 5, 6, 2, 4, 6, 1, 0, 1, 4, 0, 1, 4, 2, 2, 4, 0,
       1, 1, 3, 4, 3, 5, 2, 0, 0, 0, 2, 4, 6, 2, 4, 3, 5, 2, 5, 6, 6, 4,
       6, 1, 0, 6, 6, 6, 5, 6, 6, 3, 2, 2, 3, 4, 2, 6, 5, 4, 0, 3, 1, 3,
       2, 1, 0, 1, 2, 2, 6, 6, 1, 0, 4, 5, 4, 4, 1, 2, 3, 5, 4, 6, 3, 5,
       0, 4, 5, 4, 1, 0, 1, 5, 2, 0, 1, 4, 1, 4, 6, 5, 1, 5, 4, 0, 1, 2,
       5, 3, 1, 3, 6])

In [14]:
# Logistic Regression Classifier
lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
lr_predictions = lr_clf.predict(X_test)
lr_predictions

array([0, 4, 0, 0, 6, 0, 3, 5, 2, 0, 2, 4, 6, 3, 4, 6, 4, 6, 6, 2, 3, 2,
       4, 2, 1, 1, 1, 4, 4, 0, 4, 6, 2, 0, 0, 4, 2, 1, 0, 1, 0, 3, 6, 2,
       6, 0, 6, 0, 5, 3, 1, 1, 1, 5, 0, 2, 3, 3, 2, 3, 1, 4, 6, 0, 3, 3,
       1, 4, 0, 0, 2, 2, 0, 0, 1, 2, 3, 5, 4, 3, 1, 6, 3, 3, 2, 6, 5, 5,
       1, 2, 2, 3, 0, 1, 3, 0, 1, 2, 4, 3, 3, 2, 4, 2, 1, 2, 0, 4, 4, 3,
       6, 5, 2, 1, 0, 2, 2, 3, 6, 2, 4, 2, 6, 5, 6, 6, 5, 2, 4, 3, 4, 3,
       1, 2, 5, 4, 0, 4, 1, 4, 6, 5, 0, 0, 0, 3, 2, 4, 0, 2, 0, 0, 0, 3,
       6, 5, 6, 6, 0, 0, 5, 1, 2, 0, 3, 0, 3, 5, 0, 6, 0, 6, 3, 4, 2, 1,
       2, 2, 6, 6, 0, 3, 0, 1, 3, 2, 1, 4, 3, 3, 0, 4, 0, 2, 4, 1, 3, 4,
       4, 5, 3, 2, 4, 4, 1, 4, 5, 2, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 3,
       4, 5, 3, 1, 3, 2, 0, 4, 1, 6, 2, 4, 1, 5, 0, 2, 2, 6, 2, 0, 6, 2,
       5, 6, 3, 4, 1, 2, 4, 5, 2, 2, 0, 6, 1, 5, 6, 3, 2, 6, 4, 4, 5, 2,
       2, 4, 4, 0, 1, 4, 3, 4, 6, 6, 3, 2, 3, 4, 6, 0, 0, 2, 6, 4, 4, 5,
       2, 2, 0, 3, 2, 2, 1, 3, 0, 5, 3, 3, 6, 6, 1, 5, 0, 0, 5, 6, 2, 6,
       2, 4, 5, 3, 6, 4, 1, 6, 2, 4, 6, 3, 0, 2, 4, 1, 1, 4, 2, 2, 4, 0,
       0, 1, 3, 4, 4, 5, 6, 0, 0, 0, 2, 4, 5, 2, 4, 3, 6, 2, 5, 2, 6, 4,
       6, 0, 0, 1, 6, 1, 1, 6, 2, 3, 4, 3, 3, 4, 2, 6, 5, 4, 0, 2, 0, 3,
       2, 6, 0, 0, 2, 2, 2, 3, 1, 0, 4, 5, 4, 4, 1, 2, 3, 1, 4, 1, 3, 5,
       1, 4, 2, 4, 1, 0, 5, 5, 5, 0, 0, 4, 1, 4, 2, 2, 1, 2, 4, 0, 1, 2,
       5, 6, 6, 3, 6])

In [15]:
# Random Forest Classifier
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
rf_predictions = rf_clf.predict(X_test)
rf_predictions

array([0, 4, 0, 0, 1, 0, 3, 5, 2, 0, 2, 4, 3, 3, 4, 6, 4, 3, 2, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 5, 6, 1, 0, 4, 2, 1, 1, 1, 1, 3, 1, 1,
       5, 0, 3, 1, 2, 3, 1, 1, 1, 5, 0, 5, 3, 3, 5, 3, 1, 4, 6, 0, 3, 2,
       1, 4, 0, 1, 6, 6, 0, 0, 5, 3, 3, 5, 4, 3, 1, 2, 3, 3, 2, 2, 1, 6,
       1, 6, 6, 3, 0, 1, 2, 0, 1, 2, 5, 3, 2, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 2, 1, 0, 2, 2, 3, 6, 1, 4, 3, 2, 6, 1, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 1, 2, 5, 6, 0, 0, 1, 3, 2, 4, 0, 2, 0, 0, 1, 3,
       2, 5, 6, 5, 0, 0, 5, 1, 2, 0, 3, 0, 3, 1, 5, 6, 1, 6, 3, 4, 2, 6,
       2, 6, 2, 1, 0, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 1, 3, 2,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 2,
       4, 6, 3, 5, 3, 6, 0, 4, 5, 5, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 2, 2, 1, 2, 2, 0, 5, 2, 0, 5, 1, 6, 2, 3, 2, 1, 4, 4, 5, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 6, 2, 3, 2, 3, 4, 3, 1, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 1, 2, 0, 5, 3, 3, 6, 6, 1, 5, 0, 0, 5, 1, 6, 5,
       6, 4, 5, 3, 1, 4, 5, 6, 2, 4, 6, 1, 0, 1, 4, 0, 1, 4, 2, 2, 4, 1,
       1, 1, 3, 4, 2, 5, 2, 0, 0, 1, 2, 4, 6, 2, 4, 3, 5, 2, 5, 6, 6, 4,
       6, 1, 0, 6, 6, 6, 5, 6, 6, 3, 2, 2, 3, 4, 2, 6, 5, 4, 0, 2, 1, 3,
       2, 5, 0, 1, 2, 2, 6, 6, 5, 0, 4, 5, 4, 4, 1, 2, 3, 5, 4, 6, 3, 5,
       0, 4, 5, 4, 1, 0, 1, 5, 2, 1, 0, 4, 1, 4, 6, 5, 5, 5, 4, 0, 1, 2,
       5, 3, 1, 3, 6])

In [16]:
# Support Vector Machine (SVM) Classifier
svm_clf = SVC()
svm_clf.fit(X_train, y_train)
svm_predictions = svm_clf.predict(X_test)
svm_predictions

array([0, 4, 1, 0, 5, 0, 3, 5, 6, 0, 2, 4, 2, 3, 4, 6, 4, 3, 4, 6, 4, 5,
       4, 4, 0, 5, 6, 4, 4, 0, 4, 6, 6, 0, 0, 4, 4, 1, 0, 1, 0, 4, 5, 5,
       6, 0, 3, 1, 6, 4, 5, 0, 5, 5, 1, 6, 3, 4, 6, 2, 5, 4, 2, 1, 4, 2,
       5, 4, 0, 0, 6, 6, 0, 0, 5, 4, 3, 1, 4, 4, 1, 2, 3, 4, 6, 2, 1, 6,
       1, 5, 6, 3, 0, 5, 2, 1, 5, 2, 5, 3, 4, 6, 4, 4, 5, 6, 0, 4, 4, 4,
       2, 1, 3, 1, 0, 2, 6, 4, 6, 5, 4, 3, 2, 5, 6, 3, 6, 2, 4, 3, 4, 4,
       5, 2, 6, 4, 0, 4, 1, 2, 5, 6, 0, 0, 1, 4, 4, 4, 0, 4, 0, 0, 0, 4,
       6, 1, 6, 5, 0, 0, 1, 0, 6, 0, 3, 0, 3, 5, 0, 1, 1, 2, 4, 4, 6, 5,
       2, 6, 4, 5, 0, 4, 0, 1, 4, 4, 1, 4, 3, 3, 0, 4, 0, 5, 4, 1, 4, 2,
       4, 1, 4, 4, 4, 4, 1, 4, 5, 6, 3, 4, 1, 2, 0, 4, 4, 0, 5, 3, 4, 4,
       4, 5, 4, 5, 3, 2, 0, 4, 1, 5, 5, 4, 5, 6, 1, 6, 6, 6, 3, 0, 6, 2,
       1, 4, 3, 4, 5, 4, 2, 1, 5, 4, 0, 5, 5, 6, 2, 4, 6, 6, 4, 4, 6, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 2, 2, 4, 2, 4, 4, 2, 0, 0, 5, 5, 4, 4, 5,
       6, 6, 1, 3, 3, 6, 1, 4, 0, 5, 4, 4, 6, 2, 0, 5, 0, 0, 1, 6, 2, 6,
       6, 4, 5, 3, 0, 4, 5, 5, 5, 4, 6, 6, 0, 0, 4, 0, 5, 4, 6, 6, 4, 0,
       0, 1, 3, 4, 4, 5, 6, 0, 0, 0, 2, 4, 6, 6, 4, 3, 1, 4, 1, 6, 6, 4,
       6, 0, 0, 1, 6, 6, 6, 6, 6, 3, 2, 4, 4, 4, 6, 5, 5, 4, 0, 4, 0, 2,
       2, 5, 0, 0, 6, 2, 6, 2, 5, 0, 4, 1, 4, 4, 5, 2, 3, 1, 4, 6, 4, 5,
       0, 4, 6, 4, 5, 0, 1, 5, 6, 0, 0, 4, 1, 4, 2, 6, 0, 5, 4, 0, 1, 4,
       6, 2, 1, 3, 5])

In [17]:
print("Decision Tree Classifier:")
print(classification_report(y_test, dt_predictions))
print("Logistic Regression Classifier:")
print(classification_report(y_test, lr_predictions))
print("Random Forest Classifier:")
print(classification_report(y_test, rf_predictions))
print("SVM Classifier:")
print(classification_report(y_test, svm_predictions))

Decision Tree Classifier:
              precision    recall  f1-score   support

           0       0.93      0.96      0.95        56
           1       0.87      0.87      0.87        62
           2       0.96      0.92      0.94        78
           3       0.93      0.95      0.94        58
           4       1.00      1.00      1.00        63
           5       0.89      0.91      0.90        56
           6       0.98      0.96      0.97        50

    accuracy                           0.94       423
   macro avg       0.94      0.94      0.94       423
weighted avg       0.94      0.94      0.94       423

Logistic Regression Classifier:
              precision    recall  f1-score   support

           0       0.74      0.93      0.83        56
           1       0.53      0.42      0.47        62
           2       0.58      0.60      0.59        78
           3       0.82      0.84      0.83        58
           4       0.90      1.00      0.95        63
           5       0.54      0.38      0.44        56
           6       0.35      0.38      0.37        50

    accuracy                           0.65       423
   macro avg       0.64      0.65      0.64       423
weighted avg       0.64      0.65      0.64       423

Random Forest Classifier:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        56
           1       0.86      0.92      0.89        62
           2       0.99      0.96      0.97        78
           3       0.97      0.98      0.97        58
           4       1.00      1.00      1.00        63
           5       0.89      0.88      0.88        56
           6       0.98      0.98      0.98        50

    accuracy                           0.96       423
   macro avg       0.96      0.95      0.95       423
weighted avg       0.96      0.96      0.96       423

SVM Classifier:
              precision    recall  f1-score   support

           0       0.71      0.88      0.78        56
           1       0.48      0.34      0.40        62
           2       0.65      0.33      0.44        78
           3       0.77      0.41      0.54        58
           4       0.56      1.00      0.72        63
           5       0.47      0.48      0.47        56
           6       0.43      0.58      0.49        50

    accuracy                           0.57       423
   macro avg       0.58      0.57      0.55       423
weighted avg       0.59      0.57      0.54       423